homework 3 - symmetry operations

In [22]:
import numpy as np

# define coordinates
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

# define objects
scalar = np.dot(a, b) #dot product
pseudoscalar = np.dot(c, np.cross(a, b)) #triple scalar product
polar_vector = c #no operation
axial_vector = np.cross(a, b) #cross product
print("original objects:", scalar, pseudoscalar, polar_vector, axial_vector)

# array 'even' if signs dont change, 'odd' if signs do change

#operations
identity = np.array(
    [[1, 0, 0]
     ,[0, 1, 0]
     ,[0, 0, 1]]
)

inversion = np.array(
               [[-1,  0,  0]
               ,[ 0, -1,  0]
               ,[ 0,  0, -1]]
)

#i got on wikipedia and looked up the definition of rotation matrices and mirror matrices
#ive taken linear algebra already i just needed a refresher
mirror_z = np.array(
    [[1, 0, 0]
     ,[0, 1, 0]
     ,[0, 0, -1]]
)

mirror_y = np.array(
    [[1, 0, 0]
     ,[0, -1, 0]
     ,[0, 0, 1]]
)

rotation_x_180 =np.array(
    [[1, 0, 0]
     ,[0, -1, 0]
     ,[0, 0, -1]]
)
#inversion
invert_scalar = np.dot(inversion @ a, inversion @ b)
invert_pseudoscalar = np.dot(inversion @ c, np.cross(inversion @ a, inversion @ b))
invert_polar = inversion @ c
invert_axial = np.cross(inversion @ a, inversion @ b)
print("inversion operation: \n", invert_scalar, "\n", invert_pseudoscalar, "\n", invert_polar, "\n", invert_axial)

#z axis mirror
mirrorZ_scalar = np.dot(mirror_z @ a, mirror_z @ b)
mirrorZ_pseudoscalar = np.dot(mirror_z @ c, np.cross(mirror_z @ a, mirror_z @ b))
mirrorZ_polar = mirror_z @ c
mirrorZ_axial = np.cross(mirror_z @ a, mirror_z @ b)
print("Z axis mirror operation: \n", mirrorZ_scalar, "\n", mirrorZ_pseudoscalar, "\n", mirrorZ_polar, "\n", mirrorZ_axial)

#y axis mirror
mirrorY_scalar = np.dot(mirror_y @ a, mirror_y @ b)
mirrorY_pseudoscalar = np.dot(mirror_y @ c, np.cross(mirror_y @ a, mirror_y @ b))
mirrorY_polar = mirror_y @ c
mirrorY_axial = np.cross(mirror_y @ a, mirror_y @ b)
print("Y axis mirror operation: \n", mirrorY_scalar, "\n", mirrorY_pseudoscalar, "\n", mirrorY_polar, "\n", mirrorY_axial)

#rotation of 180 around x
rotateX_scalar = np.dot(rotation_x_180 @ a, rotation_x_180 @ b)
rotateX_pseudoscalar = np.dot(rotation_x_180 @ c, np.cross(rotation_x_180 @ a, rotation_x_180 @ b))
rotateX_polar = rotation_x_180 @ c
rotateX_axial = np.cross(rotation_x_180 @ a, rotation_x_180 @ b)
print("Rotation of 180 degrees arund x axis operation: \n", rotateX_scalar, "\n", rotateX_pseudoscalar, "\n", rotateX_polar, "\n", rotateX_axial)


original objects: 0 1 [0 0 1] [0 0 1]
inversion operation: 
 0 
 -1 
 [ 0  0 -1] 
 [0 0 1]
Z axis mirror operation: 
 0 
 -1 
 [ 0  0 -1] 
 [0 0 1]
Y axis mirror operation: 
 0 
 -1 
 [0 0 1] 
 [ 0  0 -1]
Rotation of 180 degrees arund x axis operation: 
 0 
 1 
 [ 0  0 -1] 
 [ 0  0 -1]


# the table of operations
| 1D object    | identity | inversion | mirror_z | mirror_y | rotation_x_180 |
|--------------|----------|-----------|----------|----------|----------------|
| scalar       | 1        | 0         | 0        | 0        | 0              |
| pseudoscalar | 1        | -1        | -1       | -1       | 1              |
| polar vector | 1        | [0 0 -1]  | [0 0 -1] | [0 0 1]  | [0 0 -1]       |
| axial vector | 1        | [0 0 1]   | [0 0 1]  | [0 0 -1] | [0 0 -1]       |