homework 3 - symmetry operations

In [22]:
import numpy as np

# define coordinates
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

# define objects
scalar = np.dot(a, b) #dot product
pseudoscalar = np.dot(c, np.cross(a, b)) #triple scalar product
polar_vector = c #no operation
axial_vector = np.cross(a, b) #cross product
print("original objects:", scalar, pseudoscalar, polar_vector, axial_vector)

# array 'even' if signs dont change, 'odd' if signs do change

#operations
identity = np.array(
    [[1, 0, 0]
     ,[0, 1, 0]
     ,[0, 0, 1]]
)

inversion = np.array(
               [[-1,  0,  0]
               ,[ 0, -1,  0]
               ,[ 0,  0, -1]]
)

#i got on wikipedia and looked up the definition of rotation matrices and mirror matrices
#ive taken linear algebra already i just needed a refresher
mirror_z = np.array(
    [[1, 0, 0]
     ,[0, 1, 0]
     ,[0, 0, -1]]
)

mirror_y = np.array(
    [[1, 0, 0]
     ,[0, -1, 0]
     ,[0, 0, 1]]
)

rotation_x_180 =np.array(
    [[1, 0, 0]
     ,[0, -1, 0]
     ,[0, 0, -1]]
)
#inversion
invert_scalar = np.dot(inversion @ a, inversion @ b)
invert_pseudoscalar = np.dot(inversion @ c, np.cross(inversion @ a, inversion @ b))
invert_polar = inversion @ c
invert_axial = np.cross(inversion @ a, inversion @ b)
print("inversion operation: \n", invert_scalar, "\n", invert_pseudoscalar, "\n", invert_polar, "\n", invert_axial)

#z axis mirror
mirrorZ_scalar = np.dot(mirror_z @ a, mirror_z @ b)
mirrorZ_pseudoscalar = np.dot(mirror_z @ c, np.cross(mirror_z @ a, mirror_z @ b))
mirrorZ_polar = mirror_z @ c
mirrorZ_axial = np.cross(mirror_z @ a, mirror_z @ b)
print("Z axis mirror operation: \n", mirrorZ_scalar, "\n", mirrorZ_pseudoscalar, "\n", mirrorZ_polar, "\n", mirrorZ_axial)

#y axis mirror
mirrorY_scalar = np.dot(mirror_y @ a, mirror_y @ b)
mirrorY_pseudoscalar = np.dot(mirror_y @ c, np.cross(mirror_y @ a, mirror_y @ b))
mirrorY_polar = mirror_y @ c
mirrorY_axial = np.cross(mirror_y @ a, mirror_y @ b)
print("Y axis mirror operation: \n", mirrorY_scalar, "\n", mirrorY_pseudoscalar, "\n", mirrorY_polar, "\n", mirrorY_axial)

#rotation of 180 around x
rotateX_scalar = np.dot(rotation_x_180 @ a, rotation_x_180 @ b)
rotateX_pseudoscalar = np.dot(rotation_x_180 @ c, np.cross(rotation_x_180 @ a, rotation_x_180 @ b))
rotateX_polar = rotation_x_180 @ c
rotateX_axial = np.cross(rotation_x_180 @ a, rotation_x_180 @ b)
print("Rotation of 180 degrees arund x axis operation: \n", rotateX_scalar, "\n", rotateX_pseudoscalar, "\n", rotateX_polar, "\n", rotateX_axial)


original objects: 0 1 [0 0 1] [0 0 1]
inversion operation: 
 0 
 -1 
 [ 0  0 -1] 
 [0 0 1]
Z axis mirror operation: 
 0 
 -1 
 [ 0  0 -1] 
 [0 0 1]
Y axis mirror operation: 
 0 
 -1 
 [0 0 1] 
 [ 0  0 -1]
Rotation of 180 degrees arund x axis operation: 
 0 
 1 
 [ 0  0 -1] 
 [ 0  0 -1]


# the table of operations
| 1D object    | identity | inversion | mirror_z | mirror_y | rotation_x_180 |
|--------------|----------|-----------|----------|----------|----------------|
| scalar       | 1        | 0         | 0        | 0        | 0              |
| pseudoscalar | 1        | -1        | -1       | -1       | 1              |
| polar vector | 1        | [0 0 -1]  | [0 0 -1] | [0 0 1]  | [0 0 -1]       |
| axial vector | 1        | [0 0 1]   | [0 0 1]  | [0 0 -1] | [0 0 -1]       |

i forgot to answer the questions my bad

1. Are any of these operators redundant?
   I would argue the identity operator is redundant, since it never actually changes the object. Redundancy doesn't mean unnecessary, though, since its    important to have a constant for comparison.

2. Notice that the square of any of these terms, i.e. Q_i^2, is even under all of the symmetry operations. This is a generalization of the multiplication rules "even times even is even" and "odd times odd is even" for each symmetry. You can think about this as a sping-mass system where the energy stored in the spring is 1/2 k x^2. Each Q_i is the coordinate of a mass, and 1/2 k is whatever the coefficient of that is that gives us units of energy. Are any terms Q_i * Q_j possible? Why or why not? What about Q_i * Q_j * Q_k? These terms, if the exists, tell us how these "springs" can be coupled to each other.

   Assumptions: Q_i, Q_j, and Q_k all refer to different objects, not similar objects. I also assume that the terms 'even/odd' also refer to 'positive/negative'. In this case, I would then assume that any Q_i * Q_j cannot be odd/negative because we are assuming a physical spring-mass system and the energy cannot be negative (implies the system is releasing more energy than it absorbs), k is a constant coefficent that cannot be negative, and x cannot be a negative position, if we take our coordinate system's orgin to be at the base of the spring, which I usually would.

   With all of these assumptions, any Q_i * Q_j that produces an even/posititive result is allowable. For example, the inversion of a pseudoscalar times the Z-mirror of a polar vector would equal [0 0 1], which is even and positive. The exception would be any operator of a scalar since it would always equal 0 - then again, would a 0 array be considered even? I'm not sure, actually.

   The same logic holds for any Q_i * Q_j * Q_k that produces an even and positive result. We can take our previous example, the result [0 0 1], and multiply it by the inversion of an axial vector, and get [0 0 1], which is positive and even. 
   